import { Icon } from "@iconify/react";
import { Navbar } from "../components/header";
import { useState } from "react";
import { BASE_URL } from "../config/configs";
import Head from "next/head";
import Footer from "../components/footer";
import React from "react";
import EnquiriesModal from "../components/modals/enquiries";
import CheckoutForm from "../components/modals/checkoutModal";

export const getStaticPaths = async () => {
  const res = await fetch(`${BASE_URL}/hotels`);
  const data = await res.json();
  const paths = data.map((hotel) => {
    return {
      params: { id: hotel.id.toString() },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async (context) => {
  const id = context.params.id;
  const res = await fetch(`${BASE_URL}/hotels/` + id);
  const data = await res.json();

  return {
    props: { hotels: data },
  };
};

const Details = ({
  hotels: { title, description, imageurl, map, infoabout, location, rating },
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const [checkoutModalisOpen, setCheckoutModalIsOpen] = useState(false);
  return (
    <div>
      <Head>
        <title> {title} </title>
        <meta name="details" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="details">
        <div className="details_img_div">
          <img className="details_img" src={imageurl}></img>
        </div>
        <div className="details_text_div">
          <h3 className="details_title">{title}</h3>
          <p className="details_location">
            <Icon className="details_locationIcon" icon="akar-icons:location" />
            {location}
          </p>
          <p className="details_location">
            {rating}
            <Icon className="details_starIcon" icon="ant-design:star-filled" />
            <Icon className="details_starIcon" icon="ant-design:star-filled" />
            <Icon className="details_starIcon" icon="ant-design:star-filled" />
            <Icon className="details_starIcon" icon="ant-design:star-filled" />
            <Icon className="details_starIcon" icon="bxs:star-half" />
          </p>
          <p className="details_description">{description}</p>
          <p className="details_price">875,- a day</p>
          <p className="details_price">750,- a day, for 7 days</p>
          <div className="details_buttons">
            <a>
              <button
                className="details_booknowbtn "
                onClick={() => setCheckoutModalIsOpen(true)}
              >
                Book now
              </button>
              {checkoutModalisOpen && (
                <CheckoutForm setCheckoutModalIsOpen={setCheckoutModalIsOpen} />
              )}
              <button
                className="details_contactbtn"
                onClick={() => setIsOpen(true)}
              >
                Contact hotel
              </button>
              {isOpen && <EnquiriesModal setIsOpen={setIsOpen} />}
            </a>
          </div>
          <div className="details_infowrapper">
            <div>
              <Icon className="details_icon" icon="ic:baseline-pool" />
              <p className="details_icontext">Near ocen</p>
            </div>
            <div>
              <Icon className="details_icon" icon="fa:wifi" />
              <p className="details_icontext">Wifi</p>
            </div>
            <div>
              <Icon className="details_icon" icon="fa-solid:swimming-pool" />
              <p className="details_icontext">Pool</p>
            </div>
            <div>
              <Icon className="details_icon" icon="iconoir:air-conditioner" />
              <p className="details_icontext">Air-con</p>
            </div>
            {/* <div>
              <Icon className="details_icon" icon="ri:24-hours-fill" />
              <p className="details_icontext">24hr front-desk</p>
            </div> */}
          </div>
        </div>{" "}
      </div>
      <div className="details_bordertop"></div>
      {/* INFO ABOUT */}
      <div className="infoabout">
        <div className="infoabout_titleandinfo">
          <h3 className="infoabout_title">Learn more about this place</h3>
          <p className="infoabout_description">{infoabout}</p>
        </div>
        <div className="infoabout_googlemapdiv">
          <img className="infoabout_map" src={map}></img>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Details;
