import Head from "next/head";
import { Navbar } from "../components/header";
import Footer from "../components/footer";
import CheckoutComponent from "../components/checkoutpage";

export default function Checkoutpage() {
  return (
    <div>
      <Head>
        <title>PrimaVera</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Footer />
    </div>
  );
}
