import Head from "next/head";
import { Navbar } from "../components/header";
import { BASE_URL } from "../config/configs";
import Herobanner_Hotels from "../components/hotelspage/herobanner";
import Alternatives from "../components/hotelspage/alternatives";
import HotelCardsComponent from "../components/hotelspage/hotelcards";
import Footer from "../components/footer";

export const getStaticProps = async () => {
  const res = await fetch(`${BASE_URL}/hotels`);
  const data = await res.json();

  return {
    props: { hotels: data },
  };
};

export default function Hotelspage({ hotels }) {
  return (
    <div>
      <Head>
        <title>PrimaVera - Hotels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Herobanner_Hotels />
      <Alternatives hotelsArray={hotels} />
      <div className="hotelcard_wrapper">
        {hotels.map(({ id, title, imageurl, location, description }) => (
          <HotelCardsComponent
            key={id}
            title={title}
            imageurl={imageurl}
            location={location}
            description={description}
            id={id}
          />
        ))}
      </div>
      <Footer />
    </div>
  );
}
