import Head from "next/head";
import { Navbar } from "../components/header";
import Herobanner_Home from "../components/homepage/herobanner";
import Footer from "../components/footer";
import HomepageCountries from "../components/homepage/homepagecountries";
import Newsletter from "../components/homepage/newsletterform";

export default function Homepage() {
  return (
    <div>
      <Head>
        <title>PrimaVera</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Herobanner_Home />
      <HomepageCountries />
      <Newsletter />
      <Footer />
    </div>
  );
}
