import Head from "next/head";
import { Navbar } from "../components/header";
import Footer from "../components/footer";
import LoginComponent from "../components/login";

export default function Loginpage() {
  return (
    <div>
      <Head>
        <title>PrimaVera</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <LoginComponent />
      <Footer />
    </div>
  );
}
