import Head from "next/head";
import { Navbar } from "../components/header";
import Footer from "../components/footer";
import SignIn from "../components/signin";

export default function Homepage() {
  return (
    <div>
      <Head>
        <title>PrimaVera</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <SignIn />
      <Footer />
    </div>
  );
}
